export {default as HomeOfHead} from "./HomeOfHead"
export {default as ContentOfControl} from "./Control/ContentOfControl"
export {default as InfoControl} from "./Control/InfoControl"
export {default as TaskOfControl} from "./Control/Tasks/TaskOfControl"
export {default as EditeTask} from "./Control/Tasks/EditeTask"
